---
- hosts: pi
  remote_user: pi

  tasks:
  - name: build front
    local_action: command bash -c "cd ../front && yarn && REACT_APP_BACK_HOST='' yarn run build"
    tags:
      - front
  - name: deploy front
    synchronize:
      src: ../front/build/
      dest: /home/pi/front/
    tags:
      - front

  - name: deploy back
    synchronize:
      src: ../back/
      dest: /home/pi/back/
      rsync_opts:
        - "--exclude=codes.yml"
        - "--exclude=lock_state.yml"
        - "--exclude=acolock.sqlite"
    notify:
      - restart back
    tags:
      - back
      - back_setup

  - name: setup back
    shell: /home/pi/back/setup_environment
    tags:
      - back_setup

  - name: migrate
    shell: |
      cd /home/pi/back/
      export LC_ALL=C.UTF-8
      export LANG=C.UTF-8
      . venv/bin/activate
      export FLASK_APP=acolock
      flask db upgrade
    tags:
      - back
      - migrate

  - name: Ensure socket is running
    become: yes
    service:
      name: acolock_back.socket
      state: started

  handlers:
  - name: restart back
    become: yes
    service:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: "acolock_back.socket", state: "stopped" }
      - { name: "acolock_back.service", state: "stopped" }
      - { name: "acolock_back.socket", state: "started" }
      - { name: "acolock_back.service", state: "started" }
