---
- hosts: pi
  remote_user: pi

  tasks:
  - name: build front
    local_action: command bash -c "cd ../front && yarn && REACT_APP_BACK_HOST='' yarn run build"
    tags:
      - front
  - name: deploy front
    synchronize:
      src: ../front/build/
      dest: /home/pi/front/
    tags:
      - front

  - name: deploy back
    synchronize:
      src: ../back/
      dest: /home/pi/back/
      rsync_opts:
        - "--exclude=codes.yml"
        - "--exclude=lock_state.yml"
    notify:
      - restart back
    tags:
      - back
      - back_setup

  - name: setup back
    shell: /home/pi/back/setup_environment
    tags:
      - back_setup

  - name: create lock control directory
    file:
      path: /home/pi/lock_control
      state: absent

  - name: Ensure socket is running
    become: yes
    service:
      name: acolock_back.socket
      state: started

  handlers:
  - name: restart back
    become: yes
    service:
      name: acolock_back.service
      state: restarted
